cod_ies: 162
razon_social: INSTITUTO PROFESIONAL SAN SEBASTIAN
casa_central:
  nombre_identificacion: INSTITUTO PROFESIONAL SAN SEBASTIAN
  comuna: PROVIDENCIA
  direccion: MIGUEL CLARO 337
fecha_corte: 2026-06-30
proceso: Infraestructura y Recursos Educacionales
id_carga: 16770
