import fs from 'node:fs/promises';
import { FileBlob, SpreadsheetFile } from '@oai/artifact-tool';
const root='/Users/alexi/Documents/GitHub/avance_curricular/oferta_academica_2027';
const h=`/Users/alexi/Library/CloudStorage/OneDrive-InstitutoProfesionalSanSebastián/Datos DAI (RAW) - 1.1 Datos crudos/1.2.1 Datos Institucionales/1.2.1.1 SIES/Enviados/Oferta académica/2026`;
const out=`${root}/06_validaciones/comparativo_oferta_2026_2027/RESUMEN_EJECUTIVO_OFERTA_2026_2027.xlsx`;
const files={"CSV 2027 E1":`${root}/07_resultados/cargas_congeladas/20260817_155153_etapa1_areas_vigencia_fecha/CARGA_ETAPA1_OFERTA_ACADEMICA_2027_FINAL_VIGENCIA_Y_FECHA_CORRECTAS.csv`,"CSV 2027 E2":`${root}/09_respaldo/cargas_congeladas/20260828_etapa2_carga_17451/28-08-2026_13-17-17_Oferta-Académica-TP-Nueva-2027.csv`,"CSV 2027 E3":`${root}/09_respaldo/cargas_congeladas/20260910_etapa3_carga_final_aceptada_pes/OFERTA_ACADEMICA_ARANCELES_2027_CARGA_02_CORREGIDA_SIN_TITULOS_20260910.csv`};
const parse=p=>(fs.readFile(p,'utf8')).then(x=>x.replace(/^\uFEFF/,'').split(/\r?\n/).filter(Boolean).map(l=>l.split(';')));
const wb=await SpreadsheetFile.importXlsx(await FileBlob.load(out)); const rep=await parse(`${root}/09_respaldo/reportes_pes_validados/20260907_reporte_5910_etapa1_2/5910 Oferta Académica Vigente y Nueva Validada 2027 TP Adscritas.csv`); const h48=rep[0].slice(1); const h13=['COD_SEDE','NOMBRE_SEDE','COD_CARRERA','NOMBRE_CARRERA','MODALIDAD','COD_JORNADA','VERSION','FORMATO_VALOR','VALOR_MATRICULA_ANUAL','COSTO_TITULACION','VALOR_CERTIFICADO_DIPLOMA','ARANCEL_ANUAL','VIGENCIA_CARRERA'];
for(const [name,p] of Object.entries(files)){const s=wb.worksheets.add(name);const rows=await parse(p);const header=name.endsWith('E3')?h13:h48;s.getRangeByIndexes(0,0,1,header.length).values=[header];s.getRangeByIndexes(1,0,rows.length,header.length).values=rows;s.getUsedRange().format.font.name='Arial';s.getUsedRange().format.font.size=10;s.getRangeByIndexes(0,0,1,header.length).format.fill='#D9EAF7';s.getRangeByIndexes(0,0,1,header.length).format.font.bold=true;s.getRangeByIndexes(0,0,rows.length+1,header.length).format.wrapText=true;s.getRange('A:AV').format.columnWidth=18;s.freezePanes.freezeRows(1);}
wb.worksheets.getItem('Resumen ejecutivo').getRange('K7:M7').values=[['n.a.','n.a.','n.a.']];
await wb.recalculate();const b=await SpreadsheetFile.exportXlsx(wb);await b.save(out);console.log(out);
