# -*- coding: utf-8 -*-
# Fase 3: Contrato de columnas Etapa 2 (Oferta Academica Nueva TP Adscritas)
# Fuente primaria: Instructivo Oferta Academica-Acceso CFT-IP 2027, Anexo 2 (paginas 35-41)
# y Anexo 4 (paginas 57-64, bloque especifico "Oferta Academica Nueva" paginas 61-64).
import json, os

BASE = os.path.expanduser("~/mnt/avance_curricular/oferta_academica_2027")
OUT = os.path.join(BASE, "11_gobernanza")
os.makedirs(OUT, exist_ok=True)
MANUAL = "Instructivo_Oferta_Academica-Acceso_CFT-IP 2027.txt"
STAMP = "20260827"

def col(**kw):
    d = {
        "posicion": None, "letra": None, "nombre_oficial": None, "descripcion": None,
        "tipo": None, "largo": "No especificado por el manual", "dominio": None,
        "obligatorio_o_condicional": None, "regla_detonadora": None,
        "permite_vacio": None, "permite_cero": None, "permite_menos1": None,
        "regla_cruzada": None, "fuente": MANUAL, "pagina": None, "linea": None,
        "estado_respaldo": "RESPALDADO_ESTRUCTURA_MANUAL_PAG35_41",
    }
    d.update(kw)
    return d

C = []
C.append(col(posicion=1,letra="A",nombre_oficial="COD_SEDE",descripcion="Codigo de la sede en la que se imparte el programa.",tipo="numerico",dominio="Codigos correspondientes a la institucion (catalogo propio de sedes SIES, no normalizable por similitud)",obligatorio_o_condicional="Obligatorio. Modificable",regla_detonadora="siempre",permite_vacio="NO",permite_cero="N/A (no aplica valor 0 como codigo generico salvo que exista en catalogo)",permite_menos1="NO",regla_cruzada=None,pagina=35,linea=1169))
C.append(col(posicion=2,letra="B",nombre_oficial="NOMBRE_SEDE",descripcion="Nombre de la sede en la que se imparte el programa.",tipo="texto",dominio="Mayusculas A-Z sin acentos, numeros permitidos, sin abreviaciones. Debe coincidir exactamente con el registro SIES de la sede.",obligatorio_o_condicional="Obligatorio. Modificable",regla_detonadora="siempre",permite_vacio="NO",permite_cero="N/A",permite_menos1="NO",regla_cruzada="Debe corresponder exactamente a COD_SEDE (no se corrige/normaliza por similitud)",pagina=35,linea=1174))
C.append(col(posicion=3,letra="C",nombre_oficial="COD_CARRERA",descripcion="Codigo de la carrera y/o programa.",tipo="numerico",dominio="Asignado por SIES tras el cierre",obligatorio_o_condicional="Dejar en blanco (regla explicita del manual, pagina 32 y 35)",regla_detonadora="siempre",permite_vacio="SI (debe ir vacio)",permite_cero="N/A",permite_menos1="N/A",regla_cruzada="No debe cargarse en esta etapa (Anexo 4, pag. 62: 'El COD_CARRERA no debe ser cargado en esta etapa')",pagina=35,linea=1180))
C.append(col(posicion=4,letra="D",nombre_oficial="NOMBRE_CARRERA",descripcion="Nombre de la carrera y/o programa.",tipo="texto",dominio="Mayusculas A-Z sin acentos, numeros permitidos, sin abreviaciones.",obligatorio_o_condicional="Obligatorio. Modificable",regla_detonadora="siempre",permite_vacio="NO",permite_cero="N/A",permite_menos1="NO",regla_cruzada="No se pueden colocar dobles o mas espacios en blanco (Anexo4 pag.64)",pagina=35,linea=1186))
C.append(col(posicion=5,letra="E",nombre_oficial="MODALIDAD",descripcion="Modalidad en la que se imparte el programa.",tipo="numerico",dominio="1 Presencial / 2 Semipresencial / 3 No Presencial",obligatorio_o_condicional="Obligatorio. Modificable",regla_detonadora="siempre",permite_vacio="NO",permite_cero="NO",permite_menos1="NO",regla_cruzada="Determina dominio permitido de COD_JORNADA (ver regla cruzada en campo F)",pagina=35,linea=1193))
C.append(col(posicion=6,letra="F",nombre_oficial="COD_JORNADA",descripcion="Jornada en la que se imparte el programa.",tipo="numerico",dominio="1 Diurna / 2 Vespertina / 3 Semipresencial(B-Learning) / 4 A Distancia(E-Learning)",obligatorio_o_condicional="Obligatorio. Modificable",regla_detonadora="siempre",permite_vacio="NO",permite_cero="NO",permite_menos1="NO",regla_cruzada="MODALIDAD 1->JORNADA 1 o 2; MODALIDAD 2->JORNADA 3 unicamente; MODALIDAD 3->JORNADA 4 unicamente (Anexo4 pag.61)",pagina=35,linea=1199))
C.append(col(posicion=7,letra="G",nombre_oficial="VERSION",descripcion="Codigo correlativo segun las versiones existentes del programa.",tipo="numerico",dominio="No Aplica (sin catalogo)",obligatorio_o_condicional="CONTRADICTORIO: pag.35 lo declara 'Obligatorio. Modificable'; Anexo4 pag.59 y pag.64 declaran 'La VERSION no corresponde.' dentro del mismo instructivo.",regla_detonadora="N/D",permite_vacio="N/D",permite_cero="N/D",permite_menos1="N/D",regla_cruzada="CONTRADICCION_NO_RESUELTA: no se aplica ningun tratamiento automatico. Requiere consulta a SIES antes de decidir si se carga, se deja vacio o se excluye.",pagina=35,linea=1203,estado_respaldo="CONTRADICCION_INTERNA_MANUAL_PENDIENTE_CONFIRMACION"))
C.append(col(posicion=8,letra="H",nombre_oficial="COD_TIPO_PLAN_CARRERA",descripcion="Codigo del tipo de plan al que pertenece el programa.",tipo="numerico",dominio="1 Plan Regular / 2 Plan Especial / 3 Plan Regular de Continuidad",obligatorio_o_condicional="Obligatorio. Modificable",regla_detonadora="siempre",permite_vacio="NO",permite_cero="NO",permite_menos1="NO",regla_cruzada="Si es 1 (Regular), SEMESTRES_RECONOCIDOS debe ser 0 (Anexo4 pag.61; texto literal solo cita tipo 1)",pagina=35,linea=1207))
C.append(col(posicion=9,letra="I",nombre_oficial="CARACTERISTICAS_TIPO_PLAN",descripcion="Descripcion de la caracteristica especial del plan de estudios.",tipo="texto",dominio="Mayusculas A-Z y numeros. Si el tipo de plan es Regular o Regular de Continuidad, debe completarse con 'NO APLICA'.",obligatorio_o_condicional="Obligatorio. Modificable",regla_detonadora="siempre",permite_vacio="NO (Anexo4 pag.64: no puede ser nulo, si no corresponde completar con NO APLICA)",permite_cero="NO",permite_menos1="NO",regla_cruzada="Valor 'NO APLICA' solo cuando tipo de plan sea Regular o Regular de Continuidad",pagina=36,linea=1216))
C.append(col(posicion=10,letra="J",nombre_oficial="DURACION_ESTUDIOS",descripcion="Duracion del programa en semestres (segun malla curricular), sin incluir titulacion salvo que este incluida en el plan.",tipo="numerico",dominio="Entero > 0 y <= 24 (Anexo4 pag.58/63)",obligatorio_o_condicional="Obligatorio. Modificable",regla_detonadora="siempre",permite_vacio="NO",permite_cero="NO (no puede ser 0)",permite_menos1="NO",regla_cruzada="DURACION_TOTAL no puede ser menor a DURACION_ESTUDIOS",pagina=36,linea=1224))
C.append(col(posicion=11,letra="K",nombre_oficial="DURACION_TITULACION",descripcion="Duracion en semestres del proceso de titulacion.",tipo="numerico",dominio=">=0 y <=24 (Anexo4 pag.63)",obligatorio_o_condicional="Obligatorio. Modificable",regla_detonadora="siempre",permite_vacio="NO",permite_cero="SI",permite_menos1="NO",regla_cruzada="DURACION_TOTAL <= DURACION_ESTUDIOS + DURACION_TITULACION; Anexo4 pag.63: DURACION_TITULACION no puede ser mayor a DURACION_ESTUDIOS",pagina=36,linea=1231))
C.append(col(posicion=12,letra="L",nombre_oficial="DURACION_TOTAL",descripcion="Duracion total en semestres desde el ingreso hasta la certificacion final.",tipo="numerico",dominio="> 0 y <= 24 (Anexo4 pag.63/64)",obligatorio_o_condicional="Obligatorio. Modificable",regla_detonadora="siempre",permite_vacio="NO",permite_cero="NO",permite_menos1="NO",regla_cruzada="DURACION_TOTAL <= DURACION_ESTUDIOS + DURACION_TITULACION; no puede ser menor a DURACION_ESTUDIOS",pagina=36,linea=1237))
C.append(col(posicion=13,letra="M",nombre_oficial="REGIMEN",descripcion="Formato del periodo academico del programa.",tipo="numerico",dominio="1 Semestres / 2 Trimestres / 3 Anios / 4 Bimestres",obligatorio_o_condicional="Obligatorio. Modificable",regla_detonadora="siempre",permite_vacio="NO",permite_cero="NO",permite_menos1="NO",regla_cruzada="Si REGIMEN=1, DURACION_REGIMEN debe ser igual a DURACION_TOTAL (Anexo4 pag.61)",pagina=36,linea=1243))
C.append(col(posicion=14,letra="N",nombre_oficial="DURACION_REGIMEN",descripcion="Duracion formal del programa segun el regimen declarado.",tipo="numerico",dominio="> 0, no nulo (Anexo4 pag.58/63)",obligatorio_o_condicional="Obligatorio. Modificable",regla_detonadora="siempre",permite_vacio="NO",permite_cero="NO (debe ser mayor a 0)",permite_menos1="NO",regla_cruzada="No corresponde DURACION_REGIMEN para REGIMEN 2,3,4 segun Anexo4 pag.59/64 (aparente excepcion a la obligatoriedad general de pag.58/63 salvo REGIMEN=1); se registra como regla condicional por REGIMEN",pagina=36,linea=1248))
C.append(col(posicion=15,letra="O",nombre_oficial="NOMBRE_TITULO",descripcion="Nombre del titulo o certificacion final del programa.",tipo="texto",dominio="Mayusculas A-Z sin acentos, numeros permitidos, sin abreviaciones.",obligatorio_o_condicional="Obligatorio. Modificable",regla_detonadora="siempre",permite_vacio="NO",permite_cero="NO",permite_menos1="NO",regla_cruzada="No se pueden colocar dobles o mas espacios en blanco (Anexo4 pag.64); debe completarse correctamente cuando NIVEL_CARRERA es 1 o 2 (Anexo4 pag.61)",pagina=36,linea=1254))
C.append(col(posicion=16,letra="P",nombre_oficial="COD_NIVEL_GLOBAL",descripcion="Nivel global del programa.",tipo="numerico",dominio="1 Pregrado (unico valor cargable en Oferta-Acceso para adscritos)",obligatorio_o_condicional="Obligatorio. Modificable",regla_detonadora="siempre",permite_vacio="NO",permite_cero="NO",permite_menos1="NO",regla_cruzada="Debe ser 1 para instituciones adscritas al Sistema de Acceso",pagina=37,linea=1260))
C.append(col(posicion=17,letra="Q",nombre_oficial="COD_NIVEL_CARRERA",descripcion="Nivel especifico del programa.",tipo="numerico",dominio="0 Bachillerato/Ciclo Inicial/Plan Comun, 1 TNS, 2 Profesional sin Licenciatura, 3 Licenciatura No Conducente a Titulo, 4 Profesional con Licenciatura",obligatorio_o_condicional="Obligatorio. Modificable",regla_detonadora="siempre",permite_vacio="NO",permite_cero="SI",permite_menos1="NO",regla_cruzada="Determina reglas de areas de destino (ver campos V-AF) y compatibilidad de REQUISITO_INGRESO",pagina=37,linea=1265))
C.append(col(posicion=18,letra="R",nombre_oficial="ANIO_INICIO",descripcion="Anio en que el programa inicio actividades academicas.",tipo="numerico",dominio="Anexo4 (bloque Etapa2, pag.62): 'no puede ser posterior a 2026'. Sin evidencia de rango actualizado a 2027 en el instructivo.",obligatorio_o_condicional="Obligatorio. Modificable",regla_detonadora="siempre",permite_vacio="NO",permite_cero="NO",permite_menos1="NO",regla_cruzada="POSIBLE_CONTRADICCION_FECHA: para programas declarados como oferta NUEVA 2027, un tope de 2026 es sospechoso de ser texto no actualizado del ciclo anterior. No se aplica automaticamente; queda pendiente de confirmacion igual que FECHA_ADMISION_INICIAL.",pagina=37,linea=1272,estado_respaldo="LIMITE_FECHA_SIN_CONFIRMAR_2027"))
C.append(col(posicion=19,letra="S",nombre_oficial="ACREDITACION",descripcion="Acreditacion del programa (precargado inicialmente con 2).",tipo="numerico",dominio="1 Si / 2 No / 3 En proceso (estructura pag.37); Anexo4 pag.58/63 solo cita 1 Acreditada / 2 NO acreditada",obligatorio_o_condicional="Obligatorio. Modificable",regla_detonadora="siempre",permite_vacio="NO",permite_cero="NO",permite_menos1="NO",regla_cruzada="Dominio con discrepancia leve entre estructura (3 valores) y Anexo4 (2 valores); se conserva el dominio de 3 valores de la tabla de estructura por ser mas especifica, y se marca la discrepancia como informativa.",pagina=37,linea=1276,estado_respaldo="DOMINIO_CON_DISCREPANCIA_MENOR_ENTRE_SECCIONES"))
C.append(col(posicion=20,letra="T",nombre_oficial="REQUISITO_INGRESO",descripcion="Nivel educativo formal minimo exigido para ingresar.",tipo="numerico",dominio="1 Educacion Media / 2 TNS / 3 Bachillerato / 4 Ciclo Basico / 5 Plan Comun / 6 Titulo Profesional",obligatorio_o_condicional="Obligatorio. Modificable",regla_detonadora="siempre",permite_vacio="NO",permite_cero="NO",permite_menos1="NO",regla_cruzada="TNS (COD_NIVEL_CARRERA=1) no puede exigir Titulo Profesional, Licenciatura, Especialidad Medica/Odontologica, Postitulo o Magister (Anexo4 pag.58/63)",pagina=37,linea=1282))
C.append(col(posicion=21,letra="U",nombre_oficial="SEMESTRES_RECONOCIDOS",descripcion="Semestres reconocidos como condicion de acceso desde un programa de origen (Ley 21.091).",tipo="numerico",dominio=">=0 y <=14 (Anexo4 pag.57/62)",obligatorio_o_condicional="Obligatorio. Modificable",regla_detonadora="siempre",permite_vacio="NO",permite_cero="SI (0 si plan regular)",permite_menos1="NO",regla_cruzada="Si COD_TIPO_PLAN_CARRERA=1 (Regular), SEMESTRES_RECONOCIDOS debe ser 0 (Anexo4 pag.61)",pagina=37,linea=1289))
C.append(col(posicion=22,letra="V",nombre_oficial="AREA_ACTUAL",descripcion="Area actual/origen del programa segun CINE F-2013.",tipo="numerico",dominio="1 a 10 segun catalogo del instructivo (Admin/Derecho .. TIC)",obligatorio_o_condicional="Obligatorio. Modificable",regla_detonadora="siempre",permite_vacio="NO",permite_cero="NO",permite_menos1="NO",regla_cruzada="Determina cual AREA_ destino debe marcarse en 1 segun COD_NIVEL_CARRERA (0 o 1)",pagina=37,linea=1300))

for pos,letra,nombre,pagina,linea in [
 (23,"W","AREA_ADMIN_DERECHO",37,1312),(24,"X","AREA_AGRI_SILVI_PESCA_VET",38,1324),
 (25,"Y","AREA_ARTES_HUMANIDADES",38,1333),(26,"Z","AREA_CIENCIAS_NAT_MAT_ESTAD",38,1344),
 (27,"AA","AREA_CS_SOCIAL_PERIODISMO_INFO",38,1355),(28,"AB","AREA_EDUCACION",38,1363),
 (29,"AC","AREA_INGE_INDUSTRIA_CONSTRUC",38,1372),(30,"AD","AREA_SALUD_BIENESTAR",39,1384),
 (31,"AE","AREA_SERVICIOS",39,1391),(32,"AF","AREA_TECNO_INFO_COMUNICA",39,1399),
]:
    C.append(col(posicion=pos,letra=letra,nombre_oficial=nombre,
        descripcion=f"Area de destino/continuidad de beneficio ({nombre}).",
        tipo="numerico",dominio="0 No aplica beneficio de continuidad / 1 Si aplica",
        obligatorio_o_condicional="Obligatorio. Modificable",regla_detonadora="siempre",
        permite_vacio="NO",permite_cero="SI",permite_menos1="NO",
        regla_cruzada="Nivel 0 o 1: el area correspondiente al AREA_ACTUAL debe marcarse en 1, resto en 0 (max 5 areas si TNS). Nivel 2: todas en 0. Nivel 3: solo AREA_EDUCACION=1, resto 0. Nivel 4: todas en 0. (Anexo4 pag.60/61)",
        pagina=pagina,linea=linea))

C.append(col(posicion=33,letra="AG",nombre_oficial="VACANTES_PRIMER_SEMESTRE",descripcion="Cupos ofertados para el primer semestre.",tipo="numerico",dominio=">=0 (Anexo4 pag.58); no puede ser 0 si VIGENCIA_CARRERA=1 (Anexo4 pag.61)",obligatorio_o_condicional="Obligatorio. Modificable",regla_detonadora="siempre",permite_vacio="NO",permite_cero="Condicional: 0 documentado como valor valido en pag.58, pero pag.61 prohibe 0 cuando vigencia=1",permite_menos1="NO",regla_cruzada="Si VIGENCIA_CARRERA=1, no puede ser 0. El texto de la estructura (pag.39) referencia 'año 2026' al describir este campo; posible arrastre de ciclo anterior, se marca informativo.",pagina=39,linea=1406,estado_respaldo="TEXTO_ESTRUCTURA_MENCIONA_2026_REVISAR"))
C.append(col(posicion=34,letra="AH",nombre_oficial="VACANTES_SEGUNDO_SEMESTRE",descripcion="Cupos ofertados para el segundo semestre.",tipo="numerico",dominio=">=0 (Anexo4 pag.58)",obligatorio_o_condicional="Obligatorio. Modificable",regla_detonadora="siempre",permite_vacio="NO",permite_cero="SI (documentado explicitamente)",permite_menos1="NO",regla_cruzada="Misma observacion de referencia a 'año 2026' en el texto de estructura (pag.39)",pagina=39,linea=1411,estado_respaldo="TEXTO_ESTRUCTURA_MENCIONA_2026_REVISAR"))
C.append(col(posicion=35,letra="AI",nombre_oficial="FECHA_ADMISION_INICIAL",descripcion="Fecha de inicio de postulaciones al programa.",tipo="fecha",dominio="Formato DD/MM/AAAA. Anexo4 cita reiteradamente el rango 02/10/2025-03/04/2026 o 04/04/2026, SIN evidencia de un rango actualizado a 2027 en ninguna parte del instructivo.",obligatorio_o_condicional="Obligatorio si VIGENCIA_CARRERA=1 (Anexo4 pag.61)",regla_detonadora="VIGENCIA_CARRERA=1",permite_vacio="NO si vigencia=1 / debe ir vacio si vigencia=2 (no aplica a Etapa2 adscritas)",permite_cero="N/A",permite_menos1="N/A",regla_cruzada="CONTRADICCION_FECHA_NO_RESUELTA: el rango 2025-2026 corresponde presumiblemente al ciclo de admision anterior. NO se aplica por analogia al proceso 2027. Marcar como PENDIENTE_DE_CONFIRMACION hasta obtener evidencia documental o mensaje real de la plataforma con rango 2027.",pagina=39,linea=1415,estado_respaldo="CONTRADICCION_FECHA_PENDIENTE_CONFIRMACION"))
C.append(col(posicion=36,letra="AJ",nombre_oficial="ENLACE_INFO_PROGRAMA",descripcion="Enlace web con la informacion completa del programa (plan de estudio, titulo, perfil de egreso, requisitos).",tipo="texto/url",dominio="Debe iniciar con http://, https:// o www. y apuntar a la pagina especifica del programa, no a la pagina general de la institucion.",obligatorio_o_condicional="Obligatorio. Modificable",regla_detonadora="siempre",permite_vacio="Solo si VIGENCIA_CARRERA=2 (no aplica a instituciones adscritas en Etapa2, que solo usan 1 o 3)",permite_cero="NO",permite_menos1="NO",regla_cruzada="Debe redirigir a informacion especifica del programa, no a la home de la institucion",pagina=39,linea=1422))
C.append(col(posicion=37,letra="AK",nombre_oficial="LICENCIA_ENS_MEDIA",descripcion="Licencia de ensenanza media si corresponde a una via de Admision.",tipo="texto",dominio="SI / (implicito NO por simetria con NOTAS_ENS_MEDIA, aunque el manual solo documenta explicitamente 'SI')",obligatorio_o_condicional="Obligatorio. Modificable",regla_detonadora="siempre",permite_vacio="NO",permite_cero="NO",permite_menos1="NO",regla_cruzada="Anexo4 pag.59: 'se debe completar con SI' -- se registra literal; se marca como pendiente confirmar si NO es un valor valido para este campo especifico",pagina=39,linea=1429,estado_respaldo="DOMINIO_INCOMPLETO_EN_MANUAL_SOLO_CITA_SI"))
C.append(col(posicion=38,letra="AL",nombre_oficial="NOTAS_ENS_MEDIA",descripcion="Notas de ensenanza media si corresponde a una via de Admision.",tipo="texto",dominio="SI / NO",obligatorio_o_condicional="Obligatorio. Modificable",regla_detonadora="siempre",permite_vacio="NO",permite_cero="NO",permite_menos1="NO",regla_cruzada="Si NOTAS_ENS_MEDIA=NO, PROMEDIO_MIN_ENS_MEDIA debe ser 0; si =SI, debe completarse PROMEDIO_MIN_ENS_MEDIA dentro de dominio 4.00-7.00",pagina=40,linea=1436))
C.append(col(posicion=39,letra="AM",nombre_oficial="PROMEDIO_MIN_ENS_MEDIA",descripcion="Promedio minimo de ensenanza media exigido.",tipo="numerico",dominio="4.00 a 7.00 (1 entero, 2 decimales). Agregar 0 si NOTAS_ENS_MEDIA=NO.",obligatorio_o_condicional="Obligatorio. Modificable",regla_detonadora="siempre",permite_vacio="NO",permite_cero="SI (0 si NOTAS_ENS_MEDIA=NO)",permite_menos1="NO",regla_cruzada="Depende de NOTAS_ENS_MEDIA",pagina=40,linea=1442))
C.append(col(posicion=40,letra="AN",nombre_oficial="RECONOCIMIENTOS_APREN_PREVIOS",descripcion="Reconocimiento de aprendizajes previos si corresponde a una via de Admision.",tipo="texto",dominio="SI / NO",obligatorio_o_condicional="Obligatorio si VIGENCIA_CARRERA=1 (Anexo4 pag.61: 'Cuando la VIGENCIA_CARRERA es 1, se debe completar el RECONOCIMIENTOS_APREN_PREVIOS')",regla_detonadora="VIGENCIA_CARRERA=1",permite_vacio="NO si vigencia=1",permite_cero="N/A",permite_menos1="N/A",regla_cruzada="BLOQUEANTE_POTENCIAL: el archivo recibido tiene esta columna 100% vacia mientras casi todos los registros declaran VIGENCIA_CARRERA=1, lo que contradice directamente esta regla del Anexo4.",pagina=40,linea=1449,estado_respaldo="RESPALDADO_ESTRUCTURA_Y_ANEXO4_OBLIGATORIO_SI_VIGENTE"))
C.append(col(posicion=41,letra="AO",nombre_oficial="EXPERIENCIA_LABORAL",descripcion="Experiencia laboral si corresponde a una via de Admision.",tipo="texto",dominio="SI / NO",obligatorio_o_condicional="Obligatorio. Modificable",regla_detonadora="siempre",permite_vacio="NO",permite_cero="NO",permite_menos1="NO",regla_cruzada="Debe completarse cuando VIGENCIA_CARRERA=1 (Anexo4 pag.62)",pagina=40,linea=1455))
C.append(col(posicion=42,letra="AP",nombre_oficial="MAIL_DIFUSION_CARRERA",descripcion="Correo para solicitar informacion del programa.",tipo="texto/email",dominio="Formato de correo valido ('MAIL_DIFUSION_CARRERA correcto', Anexo4 pag.62)",obligatorio_o_condicional="Obligatorio. Modificable",regla_detonadora="siempre",permite_vacio="NO",permite_cero="NO",permite_menos1="NO",regla_cruzada="Debe completarse cuando VIGENCIA_CARRERA=1",pagina=40,linea=1459))
C.append(col(posicion=43,letra="AQ",nombre_oficial="FORMATO_VALOR",descripcion="Formato del valor monetario (pesos o UF).",tipo="numerico",dominio="1 Pesos chilenos / 2 UF",obligatorio_o_condicional="Obligatorio. Modificable",regla_detonadora="siempre",permite_vacio="NO",permite_cero="NO",permite_menos1="NO",regla_cruzada="No puede ser nulo; debe completarse cuando VIGENCIA_CARRERA=1",pagina=40,linea=1463))
C.append(col(posicion=44,letra="AR",nombre_oficial="VALOR_MATRICULA_ANUAL",descripcion="Valor anual de matricula cobrado por la institucion.",tipo="numerico",dominio=">=0 o -1 (sin informacion; la excepcion -1 se documenta explicitamente para la etapa de Aranceles, Anexo3, condicionada a fecha de admision 23-dic o posterior; no confirmada para Etapa2)",obligatorio_o_condicional="Obligatorio. Modificable",regla_detonadora="siempre",permite_vacio="NO",permite_cero="SI (documentado)",permite_menos1="Condicional, no confirmado para Etapa2",regla_cruzada="Sin puntos ni separadores de miles; entero cuando FORMATO_VALOR=1 (pesos)",pagina=40,linea=1468,estado_respaldo="EXCEPCION_MENOS1_DOCUMENTADA_SOLO_PARA_ETAPA_ARANCELES"))
C.append(col(posicion=45,letra="AS",nombre_oficial="COSTO_TITULACION",descripcion="Costo del proceso de titulacion.",tipo="numerico",dominio=">=0",obligatorio_o_condicional="Obligatorio. Modificable",regla_detonadora="siempre",permite_vacio="NO",permite_cero="SI (0 si no corresponde, con regla explicita)",permite_menos1="NO",regla_cruzada="Debe completarse cuando VIGENCIA_CARRERA=1, con '0' si no corresponde",pagina=40,linea=1473))
C.append(col(posicion=46,letra="AT",nombre_oficial="VALOR_CERTIFICADO_DIPLOMA",descripcion="Costo del certificado o diploma.",tipo="numerico",dominio=">=0",obligatorio_o_condicional="Obligatorio. Modificable",regla_detonadora="siempre",permite_vacio="NO",permite_cero="SI (0 si no corresponde)",permite_menos1="NO",regla_cruzada="Debe completarse cuando VIGENCIA_CARRERA=1",pagina=40,linea=1478))
C.append(col(posicion=47,letra="AU",nombre_oficial="ARANCEL_ANUAL",descripcion="Valor del arancel anual del programa.",tipo="numerico",dominio=">=0 o sin informacion (-1) segun Anexo4 pag.58; debe ser >0 o -1 cuando VIGENCIA_CARRERA=1 (Anexo4 pag.61)",obligatorio_o_condicional="Obligatorio. Modificable",regla_detonadora="siempre",permite_vacio="NO",permite_cero="SI (documentado, con condicion de vigencia)",permite_menos1="SI (documentado explicitamente para este campo, a diferencia de VALOR_MATRICULA_ANUAL)",regla_cruzada="Sin puntos ni separadores de miles; entero cuando FORMATO_VALOR=1",pagina=41,linea=1485))
C.append(col(posicion=48,letra="AV",nombre_oficial="VIGENCIA_CARRERA",descripcion="Estado de vigencia del registro.",tipo="numerico",dominio="Para instituciones adscritas en Etapa2: 1 Vigente con estudiantes nuevos / 3 No vigente. El valor 2 (Vigente sin estudiantes nuevos) existe en el dominio general del instructivo pero Anexo4 pag.64 restringe Etapa2-adscritas a solo 1 o 3, indicando 'consultar a SIES' si aparece necesidad de vigencia 2.",obligatorio_o_condicional="Obligatorio. Modificable",regla_detonadora="siempre",permite_vacio="NO",permite_cero="NO",permite_menos1="NO",regla_cruzada="Vigencia 3 se usa exclusivamente para dar de baja un registro previamente cargado EN ESTA MISMA ETAPA, recargando su misma llave (pag.31-32). No debe usarse para corregir en silencio un registro aun no cargado.",pagina=41,linea=1489))

# Columna no reconocida en la estructura oficial (49 del archivo recibido)
C.append(col(posicion=49,letra="AW",nombre_oficial="SECTOR IPSS",
    descripcion="Columna presente en el archivo institucional recibido, ausente en la tabla de estructura oficial de Etapa 2 (paginas 35-41, columnas A-AV = 48 columnas).",
    tipo="texto",largo="No especificado (no es oficial)",dominio="No definido por el manual",
    obligatorio_o_condicional="NO CORRESPONDE A LA ESTRUCTURA OFICIAL DE CARGA ETAPA 2",
    regla_detonadora="N/A",permite_vacio="N/A",permite_cero="N/A",permite_menos1="N/A",
    regla_cruzada="No se elimina esta columna sin autorizacion: podria ser informacion de gestion interna de la institucion (posible clasificacion sectorial propia), pero no debe incluirse en el CSV de carga a SIES bajo ninguna circunstancia salvo que se demuestre que es un campo oficial no documentado en este instructivo.",
    pagina="35-41 (ausente)",linea="N/A",
    estado_respaldo="COLUMNA_NO_RECONOCIDA_EN_ESTRUCTURA_OFICIAL"))

contrato = {
    "proceso": "SIES Oferta Academica-Acceso 2027",
    "etapa": "Etapa 2 - Oferta Academica Nueva TP Adscritas",
    "generado": "2026-08-27",
    "fuente_primaria": MANUAL + " (paginas 35-41: estructura; paginas 57-64: Anexo 4 validaciones y advertencias)",
    "nota_metodologica": "No existe en el repositorio un archivo de estructura oficial de Etapa 2 descargado independientemente de PES. Este contrato se construye exclusivamente a partir del texto del instructivo oficial (nivel 1 de la jerarquia). Se registran explicitamente las contradicciones internas detectadas dentro del propio instructivo (VERSION, fechas 2025-2026 vs 2027, MALLA_CURRICULAR/PERFIL_EGRESO).",
    "columnas_oficiales_total": 48,
    "columnas_archivo_recibido_total": 49,
    "clasificacion_estructural_del_archivo": "FUENTE_INSTITUCIONAL_PENDIENTE_DE_CONFIRMACION_ESTRUCTURAL",
    "motivo_clasificacion": "Las columnas 1-48 del archivo recibido coinciden EXACTAMENTE en nombre y orden con la tabla de estructura oficial del instructivo (pag. 35-41). Sin embargo: (a) no existe un archivo de estructura oficial descargado independientemente de PES contra el cual confirmar de forma cruzada; (b) el archivo recibido tiene una columna 49 (SECTOR IPSS) ajena a esa estructura; (c) existen contradicciones internas no resueltas en el propio instructivo sobre el tratamiento de VERSION y sobre el rango de fechas aplicable a 2027. Por estas razones no se declara el archivo listo para carga.",
    "contradicciones_detectadas": [
        {
            "campo": "VERSION",
            "descripcion": "La tabla de estructura de Etapa 2 (pagina 35, linea 1203) declara VERSION como 'Obligatorio. Modificable', campo numerico correlativo. El Anexo 4 (pagina 59, linea 2008 y pagina 64, linea 2256) declara textualmente 'La VERSION no corresponde.' dentro del mismo instructivo y aplicable al bloque de Oferta Academica Nueva.",
            "resolucion": "NO_RESUELTA. No se aplica tratamiento automatico (ni carga, ni vaciado, ni eliminacion de la columna). Requiere consulta formal a SIES antes de definir el tratamiento de VERSION en el CSV final.",
        },
        {
            "campo": "FECHA_ADMISION_INICIAL / ANIO_INICIO",
            "descripcion": "El Anexo 4 cita reiteradamente (paginas 58-59 y 63-64) el rango 'no anterior al 02/10/2025 ni posterior al 03/04/2026 o 04/04/2026' para FECHA_ADMISION_INICIAL, y 'no puede ser posterior a 2026' para ANIO_INICIO (pagina 62). El proceso vigente corresponde a admision 2027. No se encontro en ningun punto del instructivo un rango de fechas explicito para 2027.",
            "resolucion": "NO_RESUELTA. Se marca FECHA_ADMISION_INICIAL y ANIO_INICIO como PENDIENTES_DE_CONFIRMACION. No se traslada por analogia el rango 2025-2026 ni el limite 2026.",
        },
        {
            "campo": "MALLA_CURRICULAR / PERFIL_EGRESO",
            "descripcion": "El Anexo 4, bloque especifico de Oferta Academica Nueva (pagina 61-62), incluye las reglas 'Cuando la VIGENCIA_CARRERA es 1, se debe completar la MALLA_CURRICULAR' y '...se debe completar la PERFIL_EGRESO', pero ninguno de los dos campos aparece en la tabla de estructura de columnas de Etapa 2 (pag. 35-41, 48 columnas) ni en el archivo institucional recibido.",
            "resolucion": "NO_RESUELTA. No se agregan estas columnas a la carga (regla de no agregar columnas por cuenta propia). Se registra como pendiente de confirmacion si corresponden a enlaces/antecedentes fuera del CSV (posiblemente cubiertos por el archivo institucional separado 'Mallas y perfiles de egreso.xlsx', que es solo antecedente, no fuente oficial) o si el instructivo esta usando texto no actualizado de otra etapa.",
        },
    ],
    "columnas": C,
}

json_path = os.path.join(OUT, f"REGLAS_MANUAL_ETAPA2_OFERTA_NUEVA_2027_{STAMP}.json")
with open(json_path, "w", encoding="utf-8") as f:
    json.dump(contrato, f, ensure_ascii=False, indent=2)

tsv_path = os.path.join(OUT, f"REGLAS_MANUAL_ETAPA2_OFERTA_NUEVA_2027_{STAMP}.tsv")
with open(tsv_path, "w", encoding="utf-8") as f:
    cols = ["posicion","letra","nombre_oficial","tipo","dominio","obligatorio_o_condicional","permite_vacio","permite_cero","permite_menos1","pagina","linea","estado_respaldo"]
    f.write("\t".join(cols) + "\n")
    for c in C:
        f.write("\t".join(str(c.get(k,"")).replace("\t"," ").replace("\n"," ") for k in cols) + "\n")

print("JSON:", json_path)
print("TSV:", tsv_path)
print("N columnas contrato:", len(C))
