import fs from 'node:fs/promises';
import path from 'node:path';
import { Workbook, SpreadsheetFile } from '@oai/artifact-tool';
const root='/Users/alexi/Documents/GitHub/avance_curricular/oferta_academica_2027';
const hroot='/Users/alexi/Library/CloudStorage/OneDrive-InstitutoProfesionalSanSebastián/Datos DAI (RAW) - 1.1 Datos crudos/1.2.1 Datos Institucionales/1.2.1.1 SIES/Enviados/Oferta académica/2026';
const P={h1:`${hroot}/ETAPA 1/20-08-2025_17-09-50_Oferta-Académica-TP-Vigente-Editada-2026.csv`,h2:`${hroot}/ETAPA 2/ETAPA 2.csv`,h3:`${hroot}/ETAPA 3/Carga_Aranceles_Etapa3_2026.csv`,c1:`${root}/07_resultados/cargas_congeladas/20260817_155153_etapa1_areas_vigencia_fecha/CARGA_ETAPA1_OFERTA_ACADEMICA_2027_FINAL_VIGENCIA_Y_FECHA_CORRECTAS.csv`,c2:`${root}/09_respaldo/cargas_congeladas/20260828_etapa2_carga_17451/28-08-2026_13-17-17_Oferta-Académica-TP-Nueva-2027.csv`,c3:`${root}/09_respaldo/cargas_congeladas/20260910_etapa3_carga_final_aceptada_pes/OFERTA_ACADEMICA_ARANCELES_2027_CARGA_02_CORREGIDA_SIN_TITULOS_20260910.csv`,r:`${root}/09_respaldo/reportes_pes_validados/20260907_reporte_5910_etapa1_2/5910 Oferta Académica Vigente y Nueva Validada 2027 TP Adscritas.csv`};
const out=`${root}/06_validaciones/comparativo_oferta_2026_2027/RESUMEN_EJECUTIVO_OFERTA_2026_2027.xlsx`;
const csv=async p=>(await fs.readFile(p,'utf8')).replace(/^\uFEFF/,'').split(/\r?\n/).filter(Boolean).map(x=>x.split(';').map(v=>v.replace(/^"|"$/g,'')));
const num=v=>{const x=Number(String(v??'').replace(/[^0-9-]/g,''));return String(v??'').trim()!==''&&Number.isFinite(x)?x:null};
function norm51(rs,y,s){return rs.map(r=>({y,s,name:r[3],level:r[15],mod:r[4],j:r[5],vac:(num(r[32])||0)+(num(r[33])||0),mat:num(r[46]),tar:num(r[49])}));}
function norm48(rs,y,s){return rs.map(r=>({y,s,name:r[3],level:r[15],mod:r[4],j:r[5],vac:(num(r[32])||0)+(num(r[33])||0),mat:num(r[43]),tar:num(r[46])}));}
function norm13(rs){return rs.map(r=>({y:'2027',s:'Etapa 3',name:r[3],level:'1',mod:r[4],j:r[5],vac:null,mat:num(r[8]),tar:num(r[11])}));}
const [h1,h2,h3,c1,c2,c3,rep]=await Promise.all(Object.values(P).map(csv));const all=[...norm51(h1,'2026','Etapa 1'),...norm51(h2,'2026','Etapa 2'),...norm51(h3,'2026','Etapa 3'),...norm48(c1,'2027','Etapa 1'),...norm48(c2,'2027','Etapa 2'),...norm13(c3)];
const agg=(y,s)=>{const a=all.filter(x=>x.y===y&&x.s===s), vals=k=>a.map(x=>x[k]).filter(v=>v!==null&&v>0).sort((x,z)=>x-z);const avg=k=>{const v=vals(k);return v.length?Math.round(v.reduce((q,z)=>q+z,0)/v.length):null};return{c:new Set(a.map(x=>x.name)).size,p:a.filter(x=>x.level==='1').length,pg:a.filter(x=>x.level!=='1').length,mods:[...new Set(a.map(x=>x.mod))].sort().join(', '),v:a.reduce((q,x)=>q+x.vac,0),tar:avg('tar'),mat:avg('mat'),nt:vals('tar').length,nm:vals('mat').length};};
const wb=Workbook.create(),sh=wb.worksheets.add('Resumen ejecutivo'),raw=wb.worksheets.add('Raw'),e1src=wb.worksheets.add('CSV 2027 E1'),e2src=wb.worksheets.add('CSV 2027 E2'),e3src=wb.worksheets.add('CSV 2027 E3'),notes=wb.worksheets.add('Notas');sh.showGridLines=false;raw.showGridLines=false;e1src.showGridLines=false;e2src.showGridLines=false;e3src.showGridLines=false;notes.showGridLines=false;
sh.getRange('A1:U1').merge();sh.getRange('A1').values=[['Resumen ejecutivo Oferta Académica: 2026 versus 2027']];sh.getRange('A2:U2').merge();sh.getRange('A2').values=[['Valores monetarios en pesos chilenos. Las brechas son 2027 menos 2026. La Etapa 3 no es comparable entre años sin homologar universo.']];
const head=['Etapa','Carreras 2026','Carreras 2027','Brecha carreras','Pregrado 2026','Pregrado 2027','Posgrado 2026','Posgrado 2027','Modalidades 2026','Modalidades 2027','Vacantes 2026','Vacantes 2027','Brecha vacantes','Arancel promedio 2026','Arancel promedio 2027','Brecha arancel','Matrícula promedio 2026','Matrícula promedio 2027','Brecha matrícula','Lectura ejecutiva','Comparabilidad'];sh.getRange('A4:U4').values=[head];
const rows=[];for(const s of ['Etapa 1','Etapa 2','Etapa 3']){const a=agg('2026',s),b=agg('2027',s),ok=s!=='Etapa 3';rows.push([s,a.c,b.c,ok?b.c-a.c:'n.a.',a.p,b.p,a.pg,b.pg,a.mods,b.mods,a.v,b.v,ok?b.v-a.v:'n.a.',a.tar??'n.a.',b.tar??'n.a.',ok&&a.tar&&b.tar?b.tar-a.tar:'n.a.',a.mat??'n.a.',b.mat??'n.a.',ok&&a.mat&&b.mat?b.mat-a.mat:'n.a.',s==='Etapa 1'?'Crece la cartera, pero baja la capacidad declarada.':s==='Etapa 2'?'La expansión de nuevas ofertas es el principal cambio.':'Corte financiero; no usar como crecimiento anual.',ok?'Comparable con cautelas':'No comparable: universos distintos']);}
sh.getRange('A5:U7').values=rows;const end=all.length+1;for(let r=5;r<=7;r++){sh.getRange(`D${r}`).formulas=[[`=C${r}-B${r}`]];sh.getRange(`K${r}`).formulas=[[`=SUMIFS(Raw!$G$2:$G$${end},Raw!$A$2:$A$${end},2026,Raw!$B$2:$B$${end},$A${r})`]];sh.getRange(`L${r}`).formulas=[[`=SUMIFS(Raw!$G$2:$G$${end},Raw!$A$2:$A$${end},2027,Raw!$B$2:$B$${end},$A${r})`]];sh.getRange(`M${r}`).formulas=[[`=IF(OR(NOT(ISNUMBER(K${r})),NOT(ISNUMBER(L${r}))),"n.a.",L${r}-K${r})`]];sh.getRange(`N${r}`).formulas=[[`=IFERROR(AVERAGEIFS(Raw!$H$2:$H$${end},Raw!$A$2:$A$${end},2026,Raw!$B$2:$B$${end},$A${r},Raw!$H$2:$H$${end},">0"),"n.a.")`]];sh.getRange(`O${r}`).formulas=[[`=IFERROR(AVERAGEIFS(Raw!$H$2:$H$${end},Raw!$A$2:$A$${end},2027,Raw!$B$2:$B$${end},$A${r},Raw!$H$2:$H$${end},">0"),"n.a.")`]];sh.getRange(`P${r}`).formulas=[[`=IF(OR(NOT(ISNUMBER(N${r})),NOT(ISNUMBER(O${r}))),"n.a.",O${r}-N${r})`]];sh.getRange(`Q${r}`).formulas=[[`=IFERROR(AVERAGEIFS(Raw!$I$2:$I$${end},Raw!$A$2:$A$${end},2026,Raw!$B$2:$B$${end},$A${r},Raw!$I$2:$I$${end},">0"),"n.a.")`]];sh.getRange(`R${r}`).formulas=[[`=IFERROR(AVERAGEIFS(Raw!$I$2:$I$${end},Raw!$A$2:$A$${end},2027,Raw!$B$2:$B$${end},$A${r},Raw!$I$2:$I$${end},">0"),"n.a.")`]];sh.getRange(`S${r}`).formulas=[[`=IF(OR(NOT(ISNUMBER(Q${r})),NOT(ISNUMBER(R${r}))),"n.a.",R${r}-Q${r})`]];}raw.getRangeByIndexes(0,0,1,9).values=[['Año','Etapa','Carrera','Jornada','Modalidad','Nivel global','Vacantes','Arancel anual','Matrícula anual']];raw.getRangeByIndexes(1,0,all.length,9).values=all.map(x=>[x.y,x.s,x.name,x.j,x.mod,x.level,x.vac,x.tar,x.mat]);notes.getRange('A1:B6').values=[['Campo','Criterio'],['Carreras','Nombres de carrera distintos.'],['Pregrado/Posgrado','Código de nivel global 1 versus distinto de 1.'],['Modalidades/Jornadas','Códigos originales; no se tradujeron sin respaldo oficial.'],['Arancel promedio','Promedio de valores positivos informados; vacíos, -1 y 0 no se promedian.'],['Matrícula promedio','Promedio de valores positivos informados; no se suman valores por carrera.']];
for(const s of [sh,raw,notes]){s.getUsedRange().format.font.name='Arial';s.getUsedRange().format.font.size=10;s.getUsedRange().format.wrapText=true;s.getUsedRange().format.verticalAlignment='center';}for(const r of [sh.getRange('A1:U1'),sh.getRange('A2:U2')]){r.format.fill='#1F4E78';r.format.font.color='#FFFFFF';r.format.font.bold=true;}for(const r of [sh.getRange('A4:U4'),raw.getRange('A1:I1'),notes.getRange('A1:B1')]){r.format.fill='#D9EAF7';r.format.font.bold=true;}sh.getRange('A1:U7').format.borders={style:'continuous',color:'#B7C9D6'};raw.getRangeByIndexes(0,0,all.length+1,9).format.borders={style:'continuous',color:'#D9E2F3'};notes.getRange('A1:B6').format.borders={style:'continuous',color:'#B7C9D6'};sh.getRange('A:A').format.columnWidth=14;sh.getRange('B:D').format.columnWidth=15;sh.getRange('E:H').format.columnWidth=14;sh.getRange('I:J').format.columnWidth=16;sh.getRange('K:S').format.columnWidth=17;sh.getRange('T:U').format.columnWidth=34;raw.getRange('A:I').format.columnWidth=20;notes.getRange('A:A').format.columnWidth=24;notes.getRange('B:B').format.columnWidth=90;
const qty='#,##0';const money='$#,##0';sh.getRange('B5:H7').format.numberFormat=qty;sh.getRange('K5:M7').format.numberFormat=qty;sh.getRange('N5:S7').format.numberFormat=money;raw.getRange(`G2:G${all.length+1}`).format.numberFormat=qty;raw.getRange(`H2:I${all.length+1}`).format.numberFormat=money;sh.freezePanes.freezeRows(4);raw.freezePanes.freezeRows(1);notes.freezePanes.freezeRows(1);await wb.recalculate();await fs.mkdir(path.dirname(out),{recursive:true});const b=await SpreadsheetFile.exportXlsx(wb);await b.save(out);console.log(out);
