import fs from 'node:fs/promises';
import path from 'node:path';
import { Workbook, SpreadsheetFile } from '@oai/artifact-tool';

const root = '/Users/alexi/Documents/GitHub/avance_curricular/oferta_academica_2027';
const hroot = '/Users/alexi/Library/CloudStorage/OneDrive-InstitutoProfesionalSanSebastián/Datos DAI (RAW) - 1.1 Datos crudos/1.2.1 Datos Institucionales/1.2.1.1 SIES/Enviados/Oferta académica/2026';
const out = path.join(root, '06_validaciones/comparativo_oferta_2026_2027/RESUMEN_KPI_OFERTA_2026_2027.xlsx');
const paths = {
  h1: path.join(hroot, 'ETAPA 1/20-08-2025_17-09-50_Oferta-Académica-TP-Vigente-Editada-2026.csv'),
  h2: path.join(hroot, 'ETAPA 2/ETAPA 2.csv'),
  h3: path.join(hroot, 'ETAPA 3/Carga_Aranceles_Etapa3_2026.csv'),
  c1: path.join(root, '07_resultados/cargas_congeladas/20260817_155153_etapa1_areas_vigencia_fecha/CARGA_ETAPA1_OFERTA_ACADEMICA_2027_FINAL_VIGENCIA_Y_FECHA_CORRECTAS.csv'),
  c2: path.join(root, '09_respaldo/cargas_congeladas/20260828_etapa2_carga_17451/28-08-2026_13-17-17_Oferta-Académica-TP-Nueva-2027.csv'),
  c3: path.join(root, '09_respaldo/cargas_congeladas/20260910_etapa3_carga_final_aceptada_pes/OFERTA_ACADEMICA_ARANCELES_2027_CARGA_02_CORREGIDA_SIN_TITULOS_20260910.csv'),
  c5910: path.join(root, '09_respaldo/reportes_pes_validados/20260907_reporte_5910_etapa1_2/5910 Oferta Académica Vigente y Nueva Validada 2027 TP Adscritas.csv'),
};

const split = (line) => line.split(';').map(x => x.replace(/^"|"$/g, ''));
const csv = async (p) => (await fs.readFile(p, 'utf8')).replace(/^\uFEFF/, '').split(/\r?\n/).filter(Boolean).map(split);
const n = (v) => { const x = Number(String(v ?? '').replace(/[^0-9-]/g, '')); return Number.isFinite(x) && String(v ?? '').trim() !== '' ? x : null; };
const unique = (a) => new Set(a.filter(Boolean)).size;

function rows51(rows) { return rows.map(r => ({ name:r[3], level:r[15], modality:r[4], vac1:n(r[32])||0, vac2:n(r[33])||0, matricula:n(r[46]), records:1 })); }
function rows48(rows) { return rows.map(r => ({ name:r[3], level:r[15], modality:r[4], vac1:n(r[32])||0, vac2:n(r[33])||0, matricula:n(r[43]), records:1 })); }
function rows5910(rows) { const h=rows[0]; const ix=Object.fromEntries(h.map((x,i)=>[x,i])); return rows.slice(1).map(r => ({ key:[r[ix.COD_SEDE],r[ix.NOMBRE_CARRERA],r[ix.MODALIDAD],r[ix.COD_JORNADA],r[ix.VERSION],r[ix.VIGENCIA_CARRERA]].join('|'), name:r[ix.NOMBRE_CARRERA], level:r[ix.COD_NIVEL_GLOBAL], modality:r[ix.MODALIDAD], vac1:n(r[ix.VACANTES_PRIMER_SEMESTRE])||0, vac2:n(r[ix.VACANTES_SEGUNDO_SEMESTRE])||0, matricula:n(r[ix.VALOR_MATRICULA_ANUAL]), records:1 })); }
function aggregate(rows) { const mv=rows.filter(r=>r.matricula!==null&&r.matricula>0).map(r=>r.matricula).sort((a,b)=>a-b); const m = { records:rows.length, careers:unique(rows.map(r=>r.name)), vacancies:rows.reduce((s,r)=>s+r.vac1+r.vac2,0), matriculaRecords:mv.length, matriculaMin:mv[0]??null, matriculaMax:mv.at(-1)??null, modalities:[...new Set(rows.map(r=>r.modality).filter(Boolean))].sort().join(', '), pregrado:rows.filter(r=>r.level==='1').length, posgrado:rows.filter(r=>r.level!=='1').length }; m.matriculaAvg=mv.length?Math.round(mv.reduce((s,x)=>s+x,0)/mv.length):null; m.matriculaMedian=mv.length?mv[Math.floor((mv.length-1)/2)]:null; return m; }

const [h1,h2,h3,c1,c2,c3,report] = await Promise.all(Object.values(paths).map(csv));
const r5910 = rows5910(report); const r5910ByKey = new Map(r5910.map(r=>[r.key,r]));
const r3 = (await csv(paths.c3)).map(r=>r5910ByKey.get([r[0],r[3],r[4],r[5],r[6],r[12]].join('|'))).filter(Boolean);
const sets = [
  ['2026','Etapa 1','E1 histórica (Oferta-Acceso)',rows51(h1)],
  ['2026','Etapa 2','E2 histórica (Oferta Nueva)',rows51(h2)],
  ['2026','Etapa 3','E3 histórica (corte anual)',rows51(h3)],
  ['2027','Etapa 1','E1 carga gobernada',rows48(c1)],
  ['2027','Etapa 2','E2 carga gobernada',rows48(c2)],
  ['2027','Etapa 3','E3 aceptada PES (vigencia 1)',r3],
];
const data = sets.map(([year,stage,desc,rows]) => ({year,stage,desc,rows,m:aggregate(rows)}));
const by = (year,stage) => data.find(x=>x.year===year&&x.stage===stage);
const wb = Workbook.create(); const sh=wb.worksheets.add('Resumen ejecutivo'); const strat=wb.worksheets.add('Lectura estratégica'); const price=wb.worksheets.add('Arancel por jornada'); const det=wb.worksheets.add('Detalle por etapa'); const raw=wb.worksheets.add('Raw'); const notes=wb.worksheets.add('Notas');
sh.showGridLines=false; det.showGridLines=false; notes.showGridLines=false;
sh.getRange('A1:J1').merge(); sh.getRange('A1').values=[['KPI Oferta Académica: histórico 2026 vs actual 2027']]; sh.getRange('A2:J2').merge(); sh.getRange('A2').values=[['Comparación por etapa. Las variaciones se calculan como 2027 menos 2026; “n.a.” indica alcance no comparable.']];
const hdr=['Etapa','Carreras 2026','Carreras 2027','Brecha carreras','Análisis carreras','Pregrado 2026','Pregrado 2027','Posgrado 2026','Posgrado 2027','Análisis niveles']; sh.getRange('A4:J4').values=[hdr];
const body=[]; for(const st of ['Etapa 1','Etapa 2','Etapa 3']){const a=by('2026',st),b=by('2027',st); const comparable=st!=='Etapa 3'; body.push([st,a.m.careers,b.m.careers,comparable?b.m.careers-a.m.careers:'n.a.',comparable?(b.m.careers>=a.m.careers?'Aumentó':'Disminuyó'):'No comparable: E3 2026 incluye vigencia 2 y posgrado',a.m.pregrado,b.m.pregrado,a.m.posgrado,b.m.posgrado,comparable?(b.m.posgrado>=a.m.posgrado?'Aumentó o se mantuvo':'Disminuyó'):'No comparable']);} sh.getRange('A5:J7').values=body;
sh.getRange('L4:U4').values=[['Etapa','Vacantes 2026','Vacantes 2027','Brecha vacantes','Análisis vacantes','Matrículas con valor 2026','Matrículas con valor 2027','Promedio matrícula 2026','Promedio matrícula 2027','Análisis matrícula']];
const b2=[]; for(const st of ['Etapa 1','Etapa 2','Etapa 3']){const a=by('2026',st),b=by('2027',st);const comparable=st!=='Etapa 3';b2.push([st,a.m.vacancies,b.m.vacancies,comparable?b.m.vacancies-a.m.vacancies:'n.a.',comparable?(b.m.vacancies>=a.m.vacancies?'Aumentó':'Disminuyó'):'No comparable por alcance',a.m.matriculaRecords,b.m.matriculaRecords, a.m.matriculaAvg??'n.a.',b.m.matriculaAvg??'n.a.',comparable?(b.m.matriculaAvg!==null&&a.m.matriculaAvg!==null?(b.m.matriculaAvg>=a.m.matriculaAvg?'Aumentó':'Disminuyó'):'Datos no comparables'):'No comparable']);} sh.getRange('L5:U7').values=b2;
strat.getRange('A1:F1').merge(); strat.getRange('A1').values=[['Lectura estratégica de la Oferta Académica']]; strat.getRange('A2:F2').merge(); strat.getRange('A2').values=[['Síntesis para decisión: crecimiento, composición, capacidad ofertada, nivel de matrícula y alertas de interpretación.']]; strat.getRange('A4:F4').values=[['Dimensión','Hallazgo 2026','Hallazgo 2027','Brecha / señal','Lectura estratégica','Implicancia']];
const e1a=by('2026','Etapa 1'),e1b=by('2027','Etapa 1'),e2a=by('2026','Etapa 2'),e2b=by('2027','Etapa 2'),e3a=by('2026','Etapa 3'),e3b=by('2027','Etapa 3');
strat.getRange('A5:F9').values=[['Escala de oferta',e1a.m.careers+' carreras',e1b.m.careers+' carreras','+'+(e1b.m.careers-e1a.m.careers),'La base de oferta crece en 2027.','Revisar capacidad de ejecución y consistencia de la cartera.'],['Expansión Etapa 2',e2a.m.careers+' carreras',e2b.m.careers+' carreras','+'+(e2b.m.careers-e2a.m.careers),'La incorporación de nuevas ofertas es significativamente mayor.','Priorizar validación de demanda, links, vacantes y documentación.'],['Capacidad ofertada',e1a.m.vacancies.toLocaleString('es-CL')+' vacantes',e1b.m.vacancies.toLocaleString('es-CL')+' vacantes',(e1b.m.vacancies-e1a.m.vacancies).toLocaleString('es-CL'),'Disminuye la capacidad declarada en la etapa base.','Controlar que la reducción sea intencionada y coherente con la cartera.'],['Nivel de matrícula','Promedio $'+(e1a.m.matriculaAvg??'n.a.'), 'Promedio $'+(e1b.m.matriculaAvg??'n.a.'), e1a.m.matriculaAvg&&e1b.m.matriculaAvg?(e1b.m.matriculaAvg>=e1a.m.matriculaAvg?'Aumenta':'Disminuye'):'n.a.','Se usa promedio y mediana, no suma de matrículas.','Usar como señal de posicionamiento, no como ingreso total.'],['Comparabilidad Etapa 3','Incluye vigencia 2 y posgrado','88 registros vigencia 1','No comparable','El corte financiero no representa el mismo universo.','No usar para concluir crecimiento o caída anual sin homologar universo.']];
const detail=[['Año','Etapa','Descripción','Registros','Carreras distintas','Pregrado','Posgrado','Modalidades (códigos fuente)','Vacantes totales','Registros con valor matrícula','Promedio matrícula','Mediana matrícula','Mínimo matrícula','Máximo matrícula']]; for(const x of data) detail.push([x.year,x.stage,x.desc,x.m.records,x.m.careers,x.m.pregrado,x.m.posgrado,x.m.modalities,x.m.vacancies,x.m.matriculaRecords,x.m.matriculaAvg??'n.a.',x.m.matriculaMedian??'n.a.',x.m.matriculaMin??'n.a.',x.m.matriculaMax??'n.a.']); det.getRangeByIndexes(0,0,detail.length,detail[0].length).values=detail;
const rawRows=[['Año','Etapa','Fuente','Carrera','Jornada','Modalidad','Nivel global','Vacantes totales','Valor matrícula anual','Arancel anual','Vigencia']];
function raw51(rows,year,stage,source){for(const r of rows)rawRows.push([year,stage,source,r[3],r[5],r[4],r[15],(n(r[32])||0)+(n(r[33])||0),n(r[46]),n(r[49]),r[50]]);}
function raw48(rows,year,stage,source){for(const r of rows)rawRows.push([year,stage,source,r[3],r[5],r[4],r[15],(n(r[32])||0)+(n(r[33])||0),n(r[43]),n(r[46]),r[47]]);}
function raw5910(rows,year,stage,source,filter){const h=rows[0],ix=Object.fromEntries(h.map((x,i)=>[x,i]));for(const r of rows.slice(1)){if(filter&&!filter(r,ix))continue;rawRows.push([year,stage,source,r[ix.NOMBRE_CARRERA],r[ix.COD_JORNADA],r[ix.MODALIDAD],r[ix.COD_NIVEL_GLOBAL],(n(r[ix.VACANTES_PRIMER_SEMESTRE])||0)+(n(r[ix.VACANTES_SEGUNDO_SEMESTRE])||0),n(r[ix.VALOR_MATRICULA_ANUAL]),n(r[ix.ARANCEL_ANUAL]),r[ix.VIGENCIA_CARRERA]]);}}
raw51(h1,'2026','Etapa 1','Histórico E1'); raw51(h2,'2026','Etapa 2','Histórico E2'); raw51(h3,'2026','Etapa 3','Histórico E3'); raw48(c1,'2027','Etapa 1','Carga gobernada E1'); raw48(c2,'2027','Etapa 2','Carga gobernada E2');
const c3Keys=new Set((await csv(paths.c3)).map(r=>[r[0],r[3],r[4],r[5],r[6],r[12]].join('|'))); raw5910(report,'2027','Etapa 3','Reporte 5910 para carga E3',(r,ix)=>c3Keys.has([r[ix.COD_SEDE],r[ix.NOMBRE_CARRERA],r[ix.MODALIDAD],r[ix.COD_JORNADA],r[ix.VERSION],r[ix.VIGENCIA_CARRERA]].join('|')));
raw.getRangeByIndexes(0,0,rawRows.length,rawRows[0].length).values=rawRows;
price.getRange('A1:H1').merge(); price.getRange('A1').values=[['Arancel anual promedio por jornada']]; price.getRange('A2:H2').merge(); price.getRange('A2').values=[['Fórmulas calculadas directamente sobre la hoja Raw. Los códigos de jornada se mantienen como fueron entregados por la fuente.']]; price.getRange('A4:H4').values=[['Etapa','Jornada','Registros 2026','Registros 2027','Arancel promedio 2026','Arancel promedio 2027','Brecha','Lectura']];
const journeys=[...new Set(rawRows.slice(1).map(r=>r[4]).filter(Boolean))].sort(); const pr=[]; for(const st of ['Etapa 1','Etapa 2','Etapa 3']) for(const j of journeys){const row=5+pr.length;pr.push([st,j,`=COUNTIFS(Raw!$B$2:$B$${rawRows.length},$A${row},Raw!$A$2:$A$${rawRows.length},2026,Raw!$E$2:$E$${rawRows.length},$B${row},Raw!$J$2:$J$${rawRows.length},">0")`,`=COUNTIFS(Raw!$B$2:$B$${rawRows.length},$A${row},Raw!$A$2:$A$${rawRows.length},2027,Raw!$E$2:$E$${rawRows.length},$B${row},Raw!$J$2:$J$${rawRows.length},">0")`,`=IFERROR(AVERAGEIFS(Raw!$J$2:$J$${rawRows.length},Raw!$B$2:$B$${rawRows.length},$A${row},Raw!$A$2:$A$${rawRows.length},2026,Raw!$E$2:$E$${rawRows.length},$B${row},Raw!$J$2:$J$${rawRows.length},">0"),"n.a.")`,`=IFERROR(AVERAGEIFS(Raw!$J$2:$J$${rawRows.length},Raw!$B$2:$B$${rawRows.length},$A${row},Raw!$A$2:$A$${rawRows.length},2027,Raw!$E$2:$E$${rawRows.length},$B${row},Raw!$J$2:$J$${rawRows.length},">0"),"n.a.")`,`=IF(OR(NOT(ISNUMBER(E${row})),NOT(ISNUMBER(F${row}))),"n.a.",F${row}-E${row})`,`=IF(G${row}="n.a.","No comparable",IF(G${row}>0,"Aumentó",IF(G${row}<0,"Disminuyó","Sin cambio")))`]);} price.getRangeByIndexes(4,0,pr.length,8).values=pr.map(r=>r.map(x=>typeof x==='string'&&x.startsWith('=')?null:x)); price.getRangeByIndexes(4,0,pr.length,8).formulas=pr.map(r=>r.map(x=>typeof x==='string'&&x.startsWith('=')?x:null));
notes.getRange('A1:B1').values=[['Aspecto','Nota']]; notes.getRange('A2:B8').values=[['Alcance','2026 corresponde a los archivos históricos archivados; 2027 corresponde a cargas gobernadas y reporte PES.'],['Carreras','Conteo de nombres de carrera distintos; registros es el conteo de programas/sede/modalidad.'],['Posgrado','Se clasifica por código de nivel global distinto de 1. No se tradujeron códigos sin respaldo adicional.'],['Modalidad','Se muestran códigos MODALIDAD tal como vienen en la fuente; no se inventaron etiquetas.'],['Vacantes','Suma VACANTES_PRIMER_SEMESTRE + VACANTES_SEGUNDO_SEMESTRE.'],['Matrícula','Se informa cantidad de registros con valor, total y promedio VALOR_MATRICULA_ANUAL; vacíos no se imputan como cero.'],['Comparabilidad','Etapa 3 2026 no es directamente comparable con Etapa 3 2027: la primera incluye vigencia 2 y posgrado; la segunda contiene solo 88 registros vigencia 1 aceptados.']];
for(const s of [sh,strat,price,det,raw,notes]){s.getUsedRange().format.font.name='Arial';s.getUsedRange().format.font.size=10;s.getUsedRange().format.verticalAlignment='center';s.getUsedRange().format.wrapText=true;}
for(const r of [sh.getRange('A1:J1'),sh.getRange('A2:J2')]){r.format.fill='#1F4E78';r.format.font.color='#FFFFFF';r.format.font.bold=true;}
for(const r of [sh.getRange('A4:J4'),sh.getRange('L4:U4'),price.getRange('A4:H4'),det.getRange('A1:N1'),raw.getRange('A1:K1'),notes.getRange('A1:B1')]){r.format.fill='#D9EAF7';r.format.font.bold=true;}
sh.getRange('A1:U7').format.borders={style:'continuous',color:'#B7C9D6'}; strat.getRange('A1:F9').format.borders={style:'continuous',color:'#B7C9D6'}; det.getRange('A1:N7').format.borders={style:'continuous',color:'#B7C9D6'}; notes.getRange('A1:B8').format.borders={style:'continuous',color:'#B7C9D6'};
sh.getRange('A:A').format.columnWidth=16;sh.getRange('B:U').format.columnWidth=16;sh.getRange('E:E').format.columnWidth=30;sh.getRange('J:J').format.columnWidth=28;sh.getRange('Q:Q').format.columnWidth=26;sh.getRange('U:U').format.columnWidth=28;strat.getRange('A:A').format.columnWidth=22;strat.getRange('B:D').format.columnWidth=24;strat.getRange('E:F').format.columnWidth=42;price.getRange('A:H').format.columnWidth=22;det.getRange('A:N').format.columnWidth=18;raw.getRange('A:K').format.columnWidth=20;notes.getRange('A:A').format.columnWidth=22;notes.getRange('B:B').format.columnWidth=100;
for(const r of [strat.getRange('A1:F1'),strat.getRange('A2:F2'),price.getRange('A1:H1'),price.getRange('A2:H2')]){r.format.fill='#1F4E78';r.format.font.color='#FFFFFF';r.format.font.bold=true;}
sh.freezePanes.freezeRows(4); strat.freezePanes.freezeRows(4); price.freezePanes.freezeRows(4); det.freezePanes.freezeRows(1); raw.freezePanes.freezeRows(1); notes.freezePanes.freezeRows(1);
await wb.recalculate(); await fs.mkdir(path.dirname(out),{recursive:true}); const blob=await SpreadsheetFile.exportXlsx(wb); await blob.save(out); console.log(out);
